plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleMemoizedHelpers:
  Max: 10

Rails/Exit:
  Exclude:
    - "spec/rails_helper.rb"