FROM ruby:3.3.6
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo
ENV RAILS_ENV=development

RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - \
 && apt-get update -qq \
 && apt-get install -y build-essential libpq-dev nodejs \
 && npm install --global yarn \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN gem install bundler
RUN gem install rails -v 7.1.6
